// Licensed under the MIT License.

using Metaschema.Loading;
using Metaschema.CodeGeneration;
using Shouldly;
using Xunit;

namespace Metaschema.Databind.CodeGen;

public class CSharpCodeGeneratorTests
{
    private static string GetTestDataPath(string relativePath) =>
        Path.Combine(AppContext.BaseDirectory, "TestData", relativePath);

    private static Model.MetaschemaModule LoadTestModule()
    {
        var loader = new ModuleLoader();
        return loader.Load(GetTestDataPath("simple-module.xml"));
    }

    [Fact]
    public void Generate_SimpleModule_ShouldProduceSingleFile()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        files.Count.ShouldBe(1);
        files.Keys.First().ShouldEndWith(".g.cs");
    }

    [Fact]
    public void Generate_SimpleModule_ShouldContainNamespace()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { Namespace = "MyApp.Models" };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("namespace MyApp.Models;");
    }

    [Fact]
    public void Generate_WithFilePerType_ShouldProduceMultipleFiles()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { FilePerType = true };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        files.Count.ShouldBeGreaterThan(1);
        files.Keys.All(k => k.EndsWith(".g.cs", StringComparison.Ordinal)).ShouldBeTrue();
    }

    [Fact]
    public void Generate_SimpleModule_ShouldContainAutoGeneratedHeader()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("// <auto-generated/>");
        content.ShouldContain("// This file was generated by Metaschema.Databind code generator.");
    }

    [Fact]
    public void Generate_WithNullableAnnotations_ShouldIncludeNullableDirective()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { NullableAnnotations = true };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("#nullable enable");
    }

    [Fact]
    public void Generate_WithoutNullableAnnotations_ShouldNotIncludeNullableDirective()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { NullableAnnotations = false };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldNotContain("#nullable enable");
    }

    [Fact]
    public void Generate_WithPublicVisibility_ShouldGeneratePublicTypes()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { Visibility = TypeVisibility.Public };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("public partial class");
    }

    [Fact]
    public void Generate_WithInternalVisibility_ShouldGenerateInternalTypes()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { Visibility = TypeVisibility.Internal };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("internal partial class");
    }

    [Fact]
    public void Generate_WithClassPrefix_ShouldPrefixClassNames()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { ClassPrefix = "My" };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("class MyDocument");
    }

    [Fact]
    public void Generate_WithClassSuffix_ShouldSuffixClassNames()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { ClassSuffix = "Model" };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("class DocumentModel");
    }

    [Fact]
    public void Generate_WithDocumentation_ShouldIncludeXmlDocs()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { IncludeDocumentation = true };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("/// <summary>");
        content.ShouldContain("/// </summary>");
    }

    [Fact]
    public void Generate_WithoutDocumentation_ShouldNotIncludeXmlDocs()
    {
        // Arrange
        var module = LoadTestModule();
        var options = new CodeGenerationOptions { IncludeDocumentation = false };
        var generator = new CSharpCodeGenerator(options);

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldNotContain("/// <summary>");
    }

    [Fact]
    public void Generate_AssemblyDefinition_ShouldGenerateClassWithAttribute()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("[MetaschemaAssembly(");
        content.ShouldContain("Name = \"document\"");
    }

    [Fact]
    public void Generate_FieldDefinition_ShouldGenerateClassWithAttribute()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("[MetaschemaField(");
    }

    [Fact]
    public void Generate_RootAssembly_ShouldIncludeRootNameAttribute()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("RootName = \"document\"");
    }

    [Fact]
    public void Generate_FlagsOnAssembly_ShouldGenerateBoundFlagProperties()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("[BoundFlag(");
    }

    [Fact]
    public void Generate_SimpleModule_ShouldIncludeUsings()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("using System;");
        content.ShouldContain("using System.Collections.Generic;");
        content.ShouldContain("using Metaschema.Binding.Attributes;");
    }

    [Fact]
    public void Generate_XmlNamespace_ShouldIncludeXmlNamespaceAttribute()
    {
        // Arrange
        var module = LoadTestModule();
        var generator = new CSharpCodeGenerator();

        // Act
        var files = generator.Generate(module);

        // Assert
        var content = files.Values.First();
        content.ShouldContain("[XmlNamespace(");
    }
}

public class CodeGenerationOptionsTests
{
    [Fact]
    public void DefaultOptions_ShouldHaveExpectedDefaults()
    {
        // Act
        var options = new CodeGenerationOptions();

        // Assert
        options.Namespace.ShouldBe("Generated");
        options.OutputPath.ShouldBeNull();
        options.Visibility.ShouldBe(TypeVisibility.Public);
        options.NullableAnnotations.ShouldBeTrue();
        options.FilePerType.ShouldBeFalse();
        options.IncludeDocumentation.ShouldBeTrue();
        options.ClassPrefix.ShouldBeNull();
        options.ClassSuffix.ShouldBeNull();
        options.FileScopedNamespaces.ShouldBeTrue();
        options.UseRecords.ShouldBeTrue();
        options.GenerateJsonContext.ShouldBeTrue();
        options.GenerateExtensionMethods.ShouldBeTrue();
    }

    [Fact]
    public void TypeVisibility_ShouldHaveExpectedValues()
    {
        // Assert
        TypeVisibility.Public.ShouldBe((TypeVisibility)0);
        TypeVisibility.Internal.ShouldBe((TypeVisibility)1);
    }
}
