// Licensed under the MIT License.

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Shouldly;
using Xunit;

namespace Metaschema.SourceGenerator;

public class MetaschemaSourceGeneratorTests
{
    [Fact]
    public void Generator_ShouldBeCreatable()
    {
        // Verify the generator type exists and can be instantiated
        var generator = new MetaschemaSourceGenerator();
        generator.ShouldNotBeNull();
    }

    [Fact]
    public void Generator_ShouldImplementIIncrementalGenerator()
    {
        var generator = new MetaschemaSourceGenerator();
        generator.ShouldBeAssignableTo<IIncrementalGenerator>();
    }

    [Fact]
    public void Generator_ShouldGenerateCodeFromMetaschemaFile()
    {
        // Arrange
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-flag name=""test-id"" as-type=""uuid"">
    <formal-name>Test Identifier</formal-name>
    <description>A unique identifier for testing.</description>
  </define-flag>

  <define-field name=""test-field"" as-type=""string"">
    <formal-name>Test Field</formal-name>
    <description>A test field for testing.</description>
    <flag ref=""test-id"" required=""yes""/>
  </define-field>

  <define-assembly name=""test-assembly"">
    <formal-name>Test Assembly</formal-name>
    <description>A test assembly for testing.</description>
    <root-name>test-root</root-name>
    <flag ref=""test-id""/>
    <model>
      <field ref=""test-field"" min-occurs=""0"" max-occurs=""unbounded""/>
    </model>
  </define-assembly>
</METASCHEMA>";

        // Act
        var (diagnostics, output) = RunGenerator(metaschemaXml, "test-schema.xml");

        // Assert
        diagnostics.ShouldBeEmpty("Generator should not produce any diagnostics");
        output.ShouldNotBeEmpty("Generator should produce output");

        var generatedSource = output[0].SourceText.ToString();
        
        // Verify generated code contains expected elements
        generatedSource.ShouldContain("// <auto-generated/>");
        generatedSource.ShouldContain("namespace Generated;");
        generatedSource.ShouldContain("public readonly partial struct TestId");
        generatedSource.ShouldContain("public partial class TestField");
        generatedSource.ShouldContain("public partial class TestAssembly");
    }

    [Fact]
    public void Generator_ShouldGenerateFlagWithCorrectType()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-flag name=""my-uuid"" as-type=""uuid"">
    <formal-name>UUID Flag</formal-name>
  </define-flag>

  <define-flag name=""my-integer"" as-type=""integer"">
    <formal-name>Integer Flag</formal-name>
  </define-flag>

  <define-flag name=""my-boolean"" as-type=""boolean"">
    <formal-name>Boolean Flag</formal-name>
  </define-flag>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "types.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        
        // UUID maps to Guid
        source.ShouldContain("public Guid Value { get; }");
        // Integer maps to long
        source.ShouldContain("public long Value { get; }");
        // Boolean maps to bool
        source.ShouldContain("public bool Value { get; }");
    }

    [Fact]
    public void Generator_ShouldGenerateCollectionProperties()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-field name=""item"" as-type=""string"">
    <formal-name>Item</formal-name>
  </define-field>

  <define-assembly name=""container"">
    <formal-name>Container</formal-name>
    <root-name>container</root-name>
    <model>
      <field ref=""item"" min-occurs=""0"" max-occurs=""unbounded""/>
    </model>
  </define-assembly>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "collection.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        source.ShouldContain("public List<Item> Item { get; set; } = new List<Item>();");
    }

    [Fact]
    public void Generator_ShouldGenerateSinglePropertyForMinMaxOne()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-field name=""single-item"" as-type=""string"">
    <formal-name>Single Item</formal-name>
  </define-field>

  <define-assembly name=""container"">
    <formal-name>Container</formal-name>
    <root-name>container</root-name>
    <model>
      <field ref=""single-item"" min-occurs=""1"" max-occurs=""1""/>
    </model>
  </define-assembly>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "single.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        source.ShouldContain("public SingleItem SingleItem { get; set; }");
        source.ShouldNotContain("List<SingleItem>");
    }

    [Fact]
    public void Generator_ShouldSkipNonMetaschemaXmlFiles()
    {
        var regularXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<root>
  <item>Not a metaschema file</item>
</root>";

        var (diagnostics, output) = RunGenerator(regularXml, "regular.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldBeEmpty("Regular XML files should be skipped");
    }

    [Fact]
    public void Generator_ShouldHandleInvalidXml()
    {
        var invalidXml = "not valid xml at all <<<<";

        var (diagnostics, output) = RunGenerator(invalidXml, "invalid.xml");

        // Should produce a warning diagnostic, not crash
        output.ShouldBeEmpty();
    }

    [Fact]
    public void Generator_ShouldConvertKebabCaseToPascalCase()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-flag name=""my-kebab-case-flag"" as-type=""string"">
    <formal-name>Kebab Case Flag</formal-name>
  </define-flag>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "kebab.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        source.ShouldContain("struct MyKebabCaseFlag");
    }

    [Fact]
    public void Generator_ShouldGenerateXmlDocumentation()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-flag name=""documented-flag"" as-type=""string"">
    <formal-name>Documented Flag</formal-name>
    <description>This flag has documentation.</description>
  </define-flag>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "docs.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        source.ShouldContain("/// <summary>");
        source.ShouldContain("Documented Flag");
        source.ShouldContain("This flag has documentation.");
    }

    [Fact]
    public void Generator_ShouldGenerateEquatableStructs()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-flag name=""equatable-flag"" as-type=""string"">
    <formal-name>Equatable Flag</formal-name>
  </define-flag>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "equatable.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        source.ShouldContain("IEquatable<EquatableFlag>");
        source.ShouldContain("public bool Equals(EquatableFlag other)");
        source.ShouldContain("public override bool Equals(object? obj)");
        source.ShouldContain("public override int GetHashCode()");
        source.ShouldContain("public static bool operator ==");
        source.ShouldContain("public static bool operator !=");
    }

    [Fact]
    public void Generator_ShouldGenerateImplicitConversions()
    {
        var metaschemaXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<METASCHEMA xmlns=""http://csrc.nist.gov/ns/oscal/metaschema/1.0"">
  <schema-name>Test Schema</schema-name>
  <schema-version>1.0.0</schema-version>
  <short-name>test</short-name>
  <namespace>http://example.com/ns/test</namespace>

  <define-flag name=""convertible-flag"" as-type=""uuid"">
    <formal-name>Convertible Flag</formal-name>
  </define-flag>
</METASCHEMA>";

        var (diagnostics, output) = RunGenerator(metaschemaXml, "convert.xml");

        diagnostics.ShouldBeEmpty();
        output.ShouldNotBeEmpty();

        var source = output[0].SourceText.ToString();
        source.ShouldContain("public static implicit operator ConvertibleFlag(Guid value)");
        source.ShouldContain("public static implicit operator Guid(ConvertibleFlag flag)");
    }

    private static (ImmutableArray<Diagnostic> Diagnostics, ImmutableArray<GeneratedSourceResult> Output) 
        RunGenerator(string xmlContent, string fileName)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            references: new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            },
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new MetaschemaSourceGenerator();

        var driver = CSharpGeneratorDriver.Create(generator)
            .AddAdditionalTexts(ImmutableArray.Create<AdditionalText>(
                new InMemoryAdditionalText(fileName, xmlContent)));

        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var diagnostics);

        var runResult = driver.GetRunResult();
        var generatorResult = runResult.Results[0];

        return (generatorResult.Diagnostics, generatorResult.GeneratedSources);
    }

    private sealed class InMemoryAdditionalText : AdditionalText
    {
        private readonly string _path;
        private readonly string _content;

        public InMemoryAdditionalText(string path, string content)
        {
            _path = path;
            _content = content;
        }

        public override string Path => _path;

        public override SourceText? GetText(System.Threading.CancellationToken cancellationToken = default)
        {
            return SourceText.From(_content);
        }
    }
}
