// <auto-generated/>
// This file was generated by the Metaschema code generator.
// Do not modify this file directly.

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Oscal.Catalog;

/// <summary>
/// JSON serialization context for oscal-catalog.
/// The System.Text.Json source generator will complete this partial class.
/// </summary>
[JsonSourceGenerationOptions(
    WriteIndented = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.KebabCaseLower,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(Catalog))]
[JsonSerializable(typeof(Metadata))]
[JsonSerializable(typeof(Group))]
[JsonSerializable(typeof(Control))]
[JsonSerializable(typeof(Parameter))]
[JsonSerializable(typeof(Part))]
[JsonSerializable(typeof(Property))]
[JsonSerializable(typeof(Link))]
[JsonSerializable(typeof(BackMatter))]
[JsonSerializable(typeof(Resource))]
[JsonSerializable(typeof(Role))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(Party))]
[JsonSerializable(typeof(ResponsibleParty))]
public partial class CatalogJsonContext : JsonSerializerContext
{
    // The STJ source generator will add implementation here
}
