// <auto-generated/>
// This file was generated by the Metaschema code generator.
// Do not modify this file directly.

#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Oscal.Catalog;

/// <summary>
/// A structured, organized collection of control information - A collection of controls.
/// </summary>
public sealed record Catalog
{
    /// <summary>
    /// Universally Unique Identifier - A globally unique identifier that can be used to reference this catalog instance elsewhere in this or other OSCAL documents. A UUID should be consistently used for a given resource across revisions of the document.
    /// </summary>
    [JsonPropertyName("uuid")]
    public required Guid Uuid { get; init; }
    
    /// <summary>
    /// Document Metadata - Provides information about the containing document, and defines concepts that are shared across the document.
    /// </summary>
    [JsonPropertyName("metadata")]
    public required Metadata Metadata { get; init; }
    
    /// <summary>
    /// Parameter - Parameters provide a mechanism for the dynamic assignment of value(s) in a control.
    /// </summary>
    [JsonPropertyName("params")]
    public IReadOnlyList<Parameter> Params { get; init; } = [];
    
    /// <summary>
    /// Control Group - A group of controls, or of groups of controls.
    /// </summary>
    [JsonPropertyName("groups")]
    public IReadOnlyList<Group> Groups { get; init; } = [];
    
    /// <summary>
    /// Control - A structured object representing a requirement or guideline, which when implemented will reduce an aspect of risk related to an information system and its information.
    /// </summary>
    [JsonPropertyName("controls")]
    public IReadOnlyList<Control> Controls { get; init; } = [];
    
    /// <summary>
    /// Back matter - A collection of resources that may be referenced from within the OSCAL document instance.
    /// </summary>
    [JsonPropertyName("back-matter")]
    public BackMatter? BackMatter { get; init; }
}
