// Licensed under the MIT License.

using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Metaschema.SourceGenerator;

/// <summary>
/// Incremental source generator for generating C# code from Metaschema modules at build time.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MetaschemaSourceGenerator : IIncrementalGenerator
{
    private static readonly XNamespace MetaschemaNamespace = "http://csrc.nist.gov/ns/oscal/metaschema/1.0";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register for AdditionalFiles with .xml extension that contain Metaschema content
        var metaschemaFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) =>
            {
                var text = file.GetText(ct);
                if (text is null) return (Path: file.Path, Content: (string?)null, IsMetaschema: false);

                var content = text.ToString();
                var isMetaschema = content.Contains("METASCHEMA") || content.Contains("metaschema");
                return (Path: file.Path, Content: content, IsMetaschema: isMetaschema);
            })
            .Where(static x => x.IsMetaschema && x.Content is not null);

        // Get global options for namespace configuration
        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.MetaschemaNamespace", out var ns);
                options.GlobalOptions.TryGetValue("build_property.MetaschemaVisibility", out var visibility);
                return new GeneratorOptions(
                    Namespace: ns ?? "Generated",
                    Visibility: visibility?.Equals("internal", StringComparison.OrdinalIgnoreCase) == true
                        ? "internal"
                        : "public"
                );
            });

        // Combine files with options
        var combined = metaschemaFiles.Combine(optionsProvider);

        // Register source output
        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var ((path, content, _), options) = source;
            if (content is null) return;

            try
            {
                var generatedCode = GenerateCode(path, content, options);
                if (generatedCode is not null)
                {
                    var fileName = Path.GetFileNameWithoutExtension(path) + ".g.cs";
                    spc.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
                }
            }
            catch (Exception ex)
            {
                // Report a diagnostic if generation fails
                var descriptor = new DiagnosticDescriptor(
                    "MTSGEN001",
                    "Metaschema Generation Error",
                    "Failed to generate code from '{0}': {1}",
                    "MetaschemaSourceGenerator",
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true);

                spc.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, path, ex.Message));
            }
        });
    }

    private static string? GenerateCode(string path, string xmlContent, GeneratorOptions options)
    {
        XDocument doc;
        try
        {
            doc = XDocument.Parse(xmlContent);
        }
        catch
        {
            return null;
        }

        var root = doc.Root;
        if (root is null) return null;

        // Check if this is a METASCHEMA document
        if (root.Name.LocalName != "METASCHEMA") return null;

        var moduleName = root.Element(MetaschemaNamespace + "short-name")?.Value ?? "Module";
        var xmlNamespace = root.Element(MetaschemaNamespace + "namespace")?.Value ?? "http://example.com/ns";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file was generated by Metaschema.SourceGenerator.");
        sb.AppendLine("// Do not modify this file directly.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {options.Namespace};");
        sb.AppendLine();

        // Generate flag definitions
        foreach (var flagDef in root.Elements(MetaschemaNamespace + "define-flag"))
        {
            GenerateFlagDefinition(sb, flagDef, options);
            sb.AppendLine();
        }

        // Generate field definitions
        foreach (var fieldDef in root.Elements(MetaschemaNamespace + "define-field"))
        {
            GenerateFieldDefinition(sb, fieldDef, options, xmlNamespace);
            sb.AppendLine();
        }

        // Generate assembly definitions
        foreach (var assemblyDef in root.Elements(MetaschemaNamespace + "define-assembly"))
        {
            GenerateAssemblyDefinition(sb, assemblyDef, options, xmlNamespace);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void GenerateFlagDefinition(StringBuilder sb, XElement flagDef, GeneratorOptions options)
    {
        var name = flagDef.Attribute("name")?.Value ?? "Unknown";
        var formalName = flagDef.Element(MetaschemaNamespace + "formal-name")?.Value;
        var description = flagDef.Element(MetaschemaNamespace + "description")?.Value;
        var dataType = flagDef.Attribute("as-type")?.Value ?? "string";
        var className = ToPascalCase(name);
        var clrType = GetClrTypeName(dataType);

        // XML documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {EscapeXml(formalName ?? name)}{(description != null ? " - " + EscapeXml(description) : "")}");
        sb.AppendLine("/// </summary>");

        // Struct declaration
        sb.AppendLine($"{options.Visibility} readonly partial struct {className} : IEquatable<{className}>");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Gets the underlying value.</summary>");
        sb.AppendLine($"    public {clrType} Value {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Initializes a new instance.</summary>");
        sb.AppendLine($"    public {className}({clrType} value) => Value = value;");
        sb.AppendLine();
        sb.AppendLine($"    public static implicit operator {className}({clrType} value) => new {className}(value);");
        sb.AppendLine($"    public static implicit operator {clrType}({className} flag) => flag.Value;");
        sb.AppendLine($"    public bool Equals({className} other) => Value.Equals(other.Value);");
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {className} other && Equals(other);");
        sb.AppendLine($"    public override int GetHashCode() => Value.GetHashCode();");
        sb.AppendLine($"    public override string? ToString() => Value.ToString();");
        sb.AppendLine($"    public static bool operator ==({className} left, {className} right) => left.Equals(right);");
        sb.AppendLine($"    public static bool operator !=({className} left, {className} right) => !left.Equals(right);");
        sb.AppendLine("}");
    }

    private static void GenerateFieldDefinition(StringBuilder sb, XElement fieldDef, GeneratorOptions options, string xmlNamespace)
    {
        var name = fieldDef.Attribute("name")?.Value ?? "Unknown";
        var formalName = fieldDef.Element(MetaschemaNamespace + "formal-name")?.Value;
        var description = fieldDef.Element(MetaschemaNamespace + "description")?.Value;
        var dataType = fieldDef.Attribute("as-type")?.Value ?? "string";
        var className = ToPascalCase(name);
        var clrType = GetClrTypeName(dataType);

        // XML documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {EscapeXml(formalName ?? name)}{(description != null ? " - " + EscapeXml(description) : "")}");
        sb.AppendLine("/// </summary>");

        // Class declaration
        sb.AppendLine($"{options.Visibility} partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Gets or sets the field value.</summary>");
        sb.AppendLine($"    public {clrType}? Value {{ get; set; }}");

        // Generate flag properties
        foreach (var flagRef in fieldDef.Elements(MetaschemaNamespace + "flag"))
        {
            var flagRefName = flagRef.Attribute("ref")?.Value ?? flagRef.Attribute("name")?.Value;
            if (flagRefName is null) continue;

            var propName = ToPascalCase(flagRefName);
            var required = flagRef.Attribute("required")?.Value == "yes";
            var nullable = required ? "" : "?";

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Gets or sets the {flagRefName} flag.</summary>");
            sb.AppendLine($"    public string{nullable} {propName} {{ get; set; }}");
        }

        sb.AppendLine("}");
    }

    private static void GenerateAssemblyDefinition(StringBuilder sb, XElement assemblyDef, GeneratorOptions options, string xmlNamespace)
    {
        var name = assemblyDef.Attribute("name")?.Value ?? "Unknown";
        var formalName = assemblyDef.Element(MetaschemaNamespace + "formal-name")?.Value;
        var description = assemblyDef.Element(MetaschemaNamespace + "description")?.Value;
        var rootName = assemblyDef.Element(MetaschemaNamespace + "root-name")?.Value;
        var className = ToPascalCase(name);

        // XML documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {EscapeXml(formalName ?? name)}{(description != null ? " - " + EscapeXml(description) : "")}");
        sb.AppendLine("/// </summary>");

        // Class declaration
        sb.AppendLine($"{options.Visibility} partial class {className}");
        sb.AppendLine("{");

        // Generate flag properties
        foreach (var flagRef in assemblyDef.Elements(MetaschemaNamespace + "flag"))
        {
            var flagRefName = flagRef.Attribute("ref")?.Value ?? flagRef.Attribute("name")?.Value;
            if (flagRefName is null) continue;

            var propName = ToPascalCase(flagRefName);
            var required = flagRef.Attribute("required")?.Value == "yes";
            var nullable = required ? "" : "?";

            sb.AppendLine($"    /// <summary>Gets or sets the {flagRefName} flag.</summary>");
            sb.AppendLine($"    public string{nullable} {propName} {{ get; set; }}");
            sb.AppendLine();
        }

        // Generate model properties
        var model = assemblyDef.Element(MetaschemaNamespace + "model");
        if (model != null)
        {
            foreach (var fieldRef in model.Descendants(MetaschemaNamespace + "field"))
            {
                var fieldRefName = fieldRef.Attribute("ref")?.Value;
                if (fieldRefName is null) continue;

                var propName = ToPascalCase(fieldRefName);
                var propTypeName = ToPascalCase(fieldRefName);
                var minOccurs = fieldRef.Attribute("min-occurs")?.Value ?? "0";
                var maxOccurs = fieldRef.Attribute("max-occurs")?.Value ?? "1";

                var isCollection = maxOccurs == "unbounded" || (int.TryParse(maxOccurs, out var max) && max > 1);

                sb.AppendLine($"    /// <summary>Gets or sets the {fieldRefName} field.</summary>");
                if (isCollection)
                {
                    sb.AppendLine($"    public List<{propTypeName}> {propName} {{ get; set; }} = new List<{propTypeName}>();");
                }
                else
                {
                    var nullable = minOccurs == "0" ? "?" : "";
                    sb.AppendLine($"    public {propTypeName}{nullable} {propName} {{ get; set; }}");
                }
                sb.AppendLine();
            }

            foreach (var assemblyRef in model.Descendants(MetaschemaNamespace + "assembly"))
            {
                var assemblyRefName = assemblyRef.Attribute("ref")?.Value;
                if (assemblyRefName is null) continue;

                var propName = ToPascalCase(assemblyRefName);
                var propTypeName = ToPascalCase(assemblyRefName);
                var minOccurs = assemblyRef.Attribute("min-occurs")?.Value ?? "0";
                var maxOccurs = assemblyRef.Attribute("max-occurs")?.Value ?? "1";

                var isCollection = maxOccurs == "unbounded" || (int.TryParse(maxOccurs, out var max) && max > 1);

                sb.AppendLine($"    /// <summary>Gets or sets the {assemblyRefName} assembly.</summary>");
                if (isCollection)
                {
                    sb.AppendLine($"    public List<{propTypeName}> {propName} {{ get; set; }} = new List<{propTypeName}>();");
                }
                else
                {
                    var nullable = minOccurs == "0" ? "?" : "";
                    sb.AppendLine($"    public {propTypeName}{nullable} {propName} {{ get; set; }}");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (c == '-' || c == '_' || c == '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }

        if (sb.Length > 0)
        {
            sb[0] = char.ToUpperInvariant(sb[0]);
        }

        return sb.ToString();
    }

    private static string GetClrTypeName(string metaschemaTypeName)
    {
        switch (metaschemaTypeName)
        {
            case "string":
            case "token":
            case "email-address":
            case "hostname":
            case "ncname":
            case "ip-v4-address":
            case "ip-v6-address":
            case "markup-line":
            case "markup-multiline":
                return "string";
            case "uri":
            case "uri-reference":
                return "Uri";
            case "uuid":
                return "Guid";
            case "integer":
                return "long";
            case "non-negative-integer":
            case "positive-integer":
                return "ulong";
            case "decimal":
                return "decimal";
            case "boolean":
                return "bool";
            case "date":
                return "DateTime";
            case "date-time":
            case "date-with-timezone":
            case "date-time-with-timezone":
                return "DateTimeOffset";
            case "base64":
                return "byte[]";
            default:
                return "string";
        }
    }

    private static string EscapeXml(string text)
    {
        if (string.IsNullOrEmpty(text)) return text;
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }

    private readonly struct GeneratorOptions
    {
        public string Namespace { get; }
        public string Visibility { get; }

        public GeneratorOptions(string ns, string visibility)
        {
            Namespace = ns;
            Visibility = visibility;
        }
    }
}
