// Licensed under the MIT License.
// Demonstrates using the Metaschema source generator to generate OSCAL types at build time.

// The types Catalog, Metadata, Control, Group, etc. are generated by the source generator
// from the OSCAL metaschema files included as AdditionalFiles in the .csproj

// Note: The source generator creates types in the namespace configured in csproj (Oscal.Types)
// You can see the generated code in the obj/Debug/net10.0/generated folder after building

using Oscal.Types;

Console.WriteLine("OSCAL Typed API - Source Generator Demo");
Console.WriteLine("=======================================");
Console.WriteLine();

// Create a catalog programmatically using the generated types
var catalog = new Catalog
{
    Uuid = Guid.NewGuid(),
    Metadata = new Metadata
    {
        Title = "Example Security Controls Catalog",
        Version = "1.0.0",
        OscalVersion = "1.1.1",
        LastModified = DateTimeOffset.UtcNow
    }
};

// Add groups and controls
catalog.Groups.Add(new Group
{
    Id = "ac",
    Title = "Access Control",
    Class = "family"
});

// Add a control to the group
catalog.Groups[0].Controls.Add(new Control
{
    Id = "ac-1",
    Title = "Policy and Procedures",
    Class = "SP800-53"
});

// Add parts to the control
catalog.Groups[0].Controls[0].Parts.Add(new Part
{
    Id = "ac-1_stmt",
    Name = "statement"
});

// Display what we created
Console.WriteLine($"Created catalog with UUID: {catalog.Uuid}");
Console.WriteLine($"  Metadata Title: {catalog.Metadata?.Title}");
Console.WriteLine($"  OSCAL Version: {catalog.Metadata?.OscalVersion}");
Console.WriteLine();
Console.WriteLine($"Groups: {catalog.Groups.Count}");
foreach (var group in catalog.Groups)
{
    Console.WriteLine($"  [{group.Id}] {group.Title}");
    Console.WriteLine($"    Controls: {group.Controls.Count}");
    foreach (var control in group.Controls)
    {
        Console.WriteLine($"      [{control.Id}] {control.Title}");
        Console.WriteLine($"        Parts: {control.Parts.Count}");
    }
}

Console.WriteLine();
Console.WriteLine("Key Benefits of Source Generator Approach:");
Console.WriteLine("  - Types generated at build time from OSCAL metaschema");
Console.WriteLine("  - No runtime code generation overhead");
Console.WriteLine("  - Full IntelliSense and compile-time type checking");
Console.WriteLine("  - Types always match the metaschema version you're targeting");
Console.WriteLine("  - Works with any metaschema, not just OSCAL");
